services:
  mongo:
    container_name: iktomi-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO-DB-USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO-DB-PASSWD}
    volumes:
      - ./mongo-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-express:
    container_name: iktomi-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO-DB-USR}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO-DB-PASSWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO-DB-USR}:${MONGO-DB-PASSWD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  iktomi-controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: iktomi-controller
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      MONGO-DB-URL: mongodb://${MONGO-DB-USR}:${MONGO-DB-PASSWD}@mongo:27017/

  iktomi-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - 8080:8080
    container_name: iktomi-ui
    depends_on:
      -  mongo
    environment:
      MONGO-DB-URL: mongodb://${MONGO-DB-USR}:${MONGO-DB-PASSWD}@mongo:27017/
