FROM python:3.13.1-slim-bookworm

WORKDIR /usr/src/app

COPY req.txt ./

RUN pip3 install --upgrade pip

RUN pip3 install -r ./req.txt

COPY . .

EXPOSE 8080

CMD ["gunicorn","--config", "gunicorn_config.py" , "app:app"]
