services:
  matsya-database:
    image: mongo:6.0
    container_name: matsya-database
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test1234
      MONGO_INITDB_DATABASE: matsya_db
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - matsya-network

  mongo-express:
    image: mongo-express:latest
    container_name: matsya-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test1234
      ME_CONFIG_MONGODB_URL: mongodb://root:test1234@matsya-database:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass123
    depends_on:
      matsya-database:
        condition: service_healthy
    networks:
      - matsya-network

  matsya-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: matsya-ui
    restart: unless-stopped
    depends_on:
      - matsya-database
    ports:
      - "3334:5000"
    volumes:
      - ./cache:/app/cache
    networks:
      - matsya-network

  matsya-controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: matsya-controller
    restart: unless-stopped
    depends_on:
      matsya-database:
        condition: service_healthy
    volumes:
      - ./cache:/app/cache
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    networks:
      - matsya-network

networks:
  matsya-network:
    driver: bridge
